// -----------------------------------------------------------------------------
// Image manifest — the ONE place to manage photos.
//
// Every image on the site is referenced by a key from this file, so swapping a
// photo never means digging through components. To replace a placeholder:
//   1. Drop the real photo into /public/images (e.g. savannah-dog-hero.jpg)
//   2. Change that entry's `src` below to the new filename
//   3. Update `alt` to describe the actual photo (important for accessibility)
//
// The starter ships with .svg placeholders generated by
// `npm run images:placeholders`. Real photos will typically be .jpg.
// -----------------------------------------------------------------------------

export type SiteImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

const IMG = "/images";

export const images = {
  hero: {
    src: `${IMG}/savannah-dog-hero.svg`,
    alt: "Savannah crouched beside a calm, happy dog outdoors",
    width: 1200,
    height: 1500,
  },
  animalCare: {
    src: `${IMG}/savannah-animal-care.svg`,
    alt: "Savannah caring for an animal, drawing on her veterinary background",
    width: 1200,
    height: 900,
  },
  portrait: {
    src: `${IMG}/savannah-portrait.svg`,
    alt: "Portrait of Savannah, founder of Simba's Compass",
    width: 1000,
    height: 1200,
  },
  simba: {
    src: `${IMG}/simba.svg`,
    alt: "Simba, the dog whose memory inspired Simba's Compass",
    width: 1200,
    height: 900,
  },
  trainingSession: {
    src: `${IMG}/training-session.svg`,
    alt: "A relaxed, focused one-on-one dog training session",
    width: 1200,
    height: 900,
  },
  ogDefault: {
    src: `${IMG}/og-default.svg`,
    alt: "Simba's Compass — compassionate dog training",
    width: 1200,
    height: 630,
  },
} satisfies Record<string, SiteImage>;

// Gallery photos. Add or remove entries freely — the grid adapts. Give every
// real photo a specific, descriptive alt for screen readers.
export const galleryImages: SiteImage[] = Array.from({ length: 12 }, (_, i) => {
  const n = String(i + 1).padStart(2, "0");
  return {
    src: `${IMG}/training-gallery-${n}.svg`,
    alt: `Savannah with a dog — training and animal-care moment ${i + 1}`,
    // Dimensions mirror the generated placeholders so the masonry layout looks
    // right immediately; update to match real photos when swapped in.
    width: [1000, 1200, 1000, 900, 1200, 1000, 1200, 1000, 960, 1200, 1040, 1200][i],
    height: [1250, 800, 1000, 1200, 900, 1300, 820, 1000, 1200, 900, 1240, 800][i],
  };
});
